"""Deterministic, artifact-derived Text-Fabric feature-header references.

This module reads emitted feature headers only. It never loads TF feature data
or invents corpus-level semantic contracts for unsupported or absent features.
"""

from __future__ import annotations

import html
import re
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

FeatureKind = Literal["node", "edge", "config"]
_MODULE_NAME = re.compile(r"[A-Za-z0-9][A-Za-z0-9_.-]*\Z")
_FEATURE_NAME = re.compile(r"[A-Za-z_][A-Za-z0-9_.@-]*\Z")
_MD_PUNCTUATION = re.compile(r"([\\`*_{}\[\]()#+.!|>-])")
_GENERATED = "<!-- generated by tf-build feature_docs; do not edit -->"
_PRIMARY = frozenset({"node", "edge", "config"})


class FeatureReferenceError(ValueError):
    """A feature header or documentation contract is ambiguous or unsafe."""


@dataclass(frozen=True, slots=True)
class FeatureHeader:
    """Exact metadata discovered in one shipped TF feature header."""

    module: str
    name: str
    kind: FeatureKind
    value_type: str | None
    edge_values: bool
    metadata: tuple[tuple[str, str], ...]
    markers: tuple[str, ...]


def _valid_module(module: str) -> None:
    if not isinstance(module, str) or _MODULE_NAME.fullmatch(module) is None:
        raise FeatureReferenceError(f"invalid TF module name: {module!r}")


def _valid_name(name: str) -> None:
    if not isinstance(name, str) or _FEATURE_NAME.fullmatch(name) is None:
        raise FeatureReferenceError(f"invalid TF feature name: {name!r}")


def _read_header(path: Path, module: str) -> FeatureHeader:
    markers: set[str] = set()
    metadata: dict[str, str] = {}
    separated = False
    try:
        with path.open("r", encoding="utf-8") as stream:
            for raw in stream:
                line = raw.rstrip("\r\n")
                if not line:
                    separated = True
                    break
                if not line.startswith("@") or not line[1:]:
                    raise FeatureReferenceError(
                        f"{path}: malformed Text-Fabric feature header"
                    )
                item = line[1:]
                if "=" in item:
                    key, value = item.split("=", 1)
                    if not key or key in metadata or key in markers or key in _PRIMARY:
                        raise FeatureReferenceError(
                            f"{path}: ambiguous or duplicate header key {key!r}"
                        )
                    metadata[key] = value
                else:
                    if item in markers or item in metadata:
                        raise FeatureReferenceError(
                            f"{path}: duplicate feature header marker {item!r}"
                        )
                    markers.add(item)
    except (OSError, UnicodeError) as exc:
        raise FeatureReferenceError(f"{path}: could not read TF feature header") from exc

    if not separated:
        raise FeatureReferenceError(f"{path}: TF feature header lacks blank separator")
    kinds = sorted(_PRIMARY & markers)
    if len(kinds) != 1:
        raise FeatureReferenceError(
            f"{path}: expected exactly one @node, @edge or @config marker"
        )
    kind: FeatureKind = kinds[0]  # type: ignore[assignment]
    edge_values = "edgeValues" in markers
    if edge_values and kind != "edge":
        raise FeatureReferenceError(f"{path}: @edgeValues requires @edge")
    if kind != "config" and metadata.get("valueType") not in ("str", "int"):
        raise FeatureReferenceError(f"{path}: invalid or absent @valueType")

    return FeatureHeader(
        module=module,
        name=path.stem,
        kind=kind,
        value_type=metadata.get("valueType") if kind != "config" else None,
        edge_values=edge_values,
        metadata=tuple(sorted(metadata.items())),
        markers=tuple(sorted(markers - _PRIMARY - {"edgeValues"})),
    )


def scan_tf_feature_headers(
    modules: Mapping[str, str | Path],
) -> tuple[FeatureHeader, ...]:
    """Inventory regular shipped .tf feature files in named TF module roots.

    Compiled .tf/ caches and other suffix-matching directories are ignored;
    symlinks and nonregular matching feature candidates fail closed.
    """
    records: list[FeatureHeader] = []
    for module, location in sorted(modules.items()):
        _valid_module(module)
        directory = Path(location)
        if directory.is_symlink():
            raise FeatureReferenceError(f"TF module directory is a symlink: {directory}")
        if not directory.is_dir():
            raise FeatureReferenceError(f"TF module directory is missing: {directory}")
        for path in sorted(directory.glob("*.tf"), key=lambda p: p.name):
            if path.is_symlink():
                raise FeatureReferenceError(f"TF feature is a symlink: {path}")
            if path.is_dir():
                continue
            if not path.is_file():
                raise FeatureReferenceError(
                    f"TF feature candidate is not a regular file: {path}"
                )
            _valid_name(path.stem)
            records.append(_read_header(path, module))
    return tuple(records)


def _safe_text(value: str) -> str:
    """Escape Markdown control characters and embedded HTML as inert prose."""
    escaped = _MD_PUNCTUATION.sub(r"\\\1", value)
    return html.escape(escaped, quote=False).replace("\n", " ").replace("\r", " ")


def render_feature_reference(
    features: Iterable[FeatureHeader],
    *,
    descriptions: Mapping[tuple[str, str], str] | None = None,
) -> dict[str, str]:
    """Render a pure deterministic namespaced Markdown page set in memory."""
    records = sorted(features, key=lambda item: (item.module, item.name))
    descriptions = {} if descriptions is None else descriptions
    pages: dict[str, str] = {}
    index = [_GENERATED, "# Text-Fabric feature reference", ""]

    for record in records:
        _valid_module(record.module)
        _valid_name(record.name)
        path = f"{record.module}/{record.name}.md"
        if path in pages:
            raise FeatureReferenceError(f"duplicate emitted TF feature: {path}")
        identifier = (record.module, record.name)
        description = descriptions.get(identifier)
        if description is None:
            description = dict(record.metadata).get("description", "")
        if not isinstance(description, str):
            raise FeatureReferenceError(f"invalid feature description for {identifier}")

        page = [
            _GENERATED,
            f"# `{record.name}`",
            "",
            f"**Module:** {_safe_text(record.module)}",
            "",
            f"**Kind:** {_safe_text(record.kind)}",
            "",
        ]
        if record.value_type is not None:
            page.extend([f"**Value type:** {_safe_text(record.value_type)}", ""])
        if record.kind == "edge":
            page.extend([f"**Edge values:** {'yes' if record.edge_values else 'no'}", ""])
        page.extend(["## Description", "", _safe_text(description) if description else "_Not declared._", ""])
        page.extend(["## Shipped header metadata", ""])
        if record.metadata:
            for key, value in record.metadata:
                page.append(f"- **{_safe_text(key)}:** {_safe_text(value)}")
        else:
            page.append("_No key/value metadata._")
        if record.markers:
            page.extend(["", "## Other header markers", ""])
            page.extend(f"- {_safe_text(marker)}" for marker in record.markers)
        pages[path] = "\n".join(page).rstrip() + "\n"
        index.append(f"- [`{record.module}/{record.name}`]({path})")

    pages["index.md"] = "\n".join(index).rstrip() + "\n"
    return dict(sorted(pages.items()))


__all__ = [
    "FeatureHeader",
    "FeatureKind",
    "FeatureReferenceError",
    "render_feature_reference",
    "scan_tf_feature_headers",
]
